# Generated by Django 5.2.5 on 2025-12-02 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Identificador del Contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Lugar')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código (Barra/Manual)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('UN', 'Unidades'), ('CJ', 'Cajas'), ('AT', 'Atados'), ('MA', 'Mallas'), ('BD', 'Bandejas'), ('LT', 'Litros')], default='KG', max_length=2, verbose_name='Formato')),
                ('tipo_origen', models.CharField(choices=[('COMPRA', 'Compra / Reventa'), ('PROPIO', 'Elaboración Propia')], default='COMPRA', max_length=10, verbose_name='Origen')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_costo', models.IntegerField(verbose_name='Precio Costo (Compra)')),
                ('precio_venta', models.IntegerField(verbose_name='Precio Venta (Público)')),
                ('stock_minimo', models.PositiveIntegerField(default=10, verbose_name='Alerta Stock Mínimo')),
                ('gestiona_lotes', models.BooleanField(default=True, verbose_name='¿Requiere Lotes y Vencimiento?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='# Lote Proveedor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Actual')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bioapp.contenedor', verbose_name='Ubicación Física')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioapp.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='contenedor',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to='bioapp.lugar', verbose_name='Ubicado en'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de Stock'), ('VENTA', 'Venta (Salida)'), ('MERMA', 'Merma (Pérdida)')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_unitario_snapshot', models.IntegerField(verbose_name='Precio al momento')),
                ('total_movimiento', models.IntegerField(editable=False, verbose_name='Total ($)')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioapp.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bioapp.producto')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contenedor',
            unique_together={('nombre', 'lugar')},
        ),
    ]
